# CC = gcc


# HEADERS = greet.h

# SOURCES = main.c greet.c

# TARGET = car


# $(TARGET): $(SOURCES) $(HEADERS)
# 	$(CC) $(SOURCES) $(HEADERS) -o $(TARGET)


matrix:
	gcc matrix.c hr.c -o matrix

run: 
	./matrix

clean:
	rm -f matrix

all:
	test run clean
