# CC = gcc


# HEADERS = greet.h

# SOURCES = main.c greet.c

# TARGET = car


# $(TARGET): $(SOURCES) $(HEADERS)
# 	$(CC) $(SOURCES) $(HEADERS) -o $(TARGET)


matrix:
	gcc main.c matrix.c hr.c -o main

run: 
	./main

clean:
	rm -f main

