# CC = gcc


# HEADERS = greet.h

# SOURCES = main.c greet.c

# TARGET = car


# $(TARGET): $(SOURCES) $(HEADERS)
# 	$(CC) $(SOURCES) $(HEADERS) -o $(TARGET)


test:
	gcc main.c greet.c -o test

run: 
	./test

clean:
	rm -f test

all:
	test run clean