# CC = gcc


# HEADERS = greet.h

# SOURCES = main.c greet.c

# TARGET = car


# $(TARGET): $(SOURCES) $(HEADERS)
# 	$(CC) $(SOURCES) $(HEADERS) -o $(TARGET)


cinema:
	gcc main.c cinema.c -o cinema

run: 
	./cinema

clean:
	rm -f cinema

